In [1]:
# Decision Trees
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("titanic.csv")
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [3]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
df=df[["Survived","Pclass","Sex","Age","Fare"]]

In [5]:
df.head()

Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [6]:
#cleaning data set
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
Fare          0
dtype: int64

In [7]:
df.groupby("Sex")["Age"].mean()

Sex
female    27.915709
male      30.726645
Name: Age, dtype: float64

In [8]:
df["Age"]=df.groupby("Sex")["Age"].transform(lambda x:x.fillna(x.mean()))

C:\Users\sonaw\AppData\Local\Temp/ipykernel_15844/2807126402.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"]=df.groupby("Sex")["Age"].transform(lambda x:x.fillna(x.mean()))


In [9]:
#changing column in numerical value
from sklearn.preprocessing import LabelEncoder

In [10]:
le = LabelEncoder()

In [11]:
df["Sex"]=le.fit_transform(df.Sex)

C:\Users\sonaw\AppData\Local\Temp/ipykernel_15844/4032670627.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Sex"]=le.fit_transform(df.Sex)


In [12]:
x=df[["Pclass","Sex","Age","Fare"]]
y=df["Survived"]

In [13]:
#spliting
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.02, random_state =1)

In [14]:
#tarining model
from sklearn.tree import DecisionTreeClassifier

In [15]:
clf=DecisionTreeClassifier(random_state=0,criterion="gini")
clf.fit(x_train,y_train)

DecisionTreeClassifier(random_state=0)

In [16]:
#checking accurcy of model testing data set
from sklearn.metrics import accuracy_score

In [17]:
precdiction_test=clf.predict(x_test)
accuracy_score(y_test,precdiction_test)

0.8333333333333334

In [18]:
#checking accurcy of model testing data set
precdiction_train=clf.predict(x_train)
accuracy_score(y_train,precdiction_train)

0.979381443298969

In [19]:
#classification report test dataset
from sklearn.metrics import classification_report,confusion_matrix

In [20]:
print(classification_report(y_test,precdiction_test))
print(confusion_matrix(y_test,precdiction_test))

              precision    recall  f1-score   support

           0       0.75      1.00      0.86         9
           1       1.00      0.67      0.80         9

    accuracy                           0.83        18
   macro avg       0.88      0.83      0.83        18
weighted avg       0.88      0.83      0.83        18

[[9 0]
 [3 6]]


In [21]:
#classification report train dataset
print(classification_report(y_train,precdiction_train))
print(confusion_matrix(y_train,precdiction_train))

              precision    recall  f1-score   support

           0       0.97      0.99      0.98       540
           1       0.99      0.95      0.97       333

    accuracy                           0.98       873
   macro avg       0.98      0.97      0.98       873
weighted avg       0.98      0.98      0.98       873

[[537   3]
 [ 15 318]]


In [22]:
#finding false postive rate and true postive rate
from sklearn.metrics import roc_curve,auc
from sklearn.metrics import roc_curve

In [23]:
dt_probs=clf.predict_proba(x_test)[:,1]

In [24]:
fpr_dt,trp_dt,thresholds_dt=roc_curve(y_test,dt_probs)

In [25]:
#score
auc_score_dt=auc(fpr_dt,trp_dt)
auc_score_dt

0.8888888888888888

In [26]:
# RandomForest
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [27]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.02, random_state =1)

In [28]:
clf=RandomForestClassifier(random_state=0,criterion="gini")
clf.fit(x_train,y_train)

RandomForestClassifier(random_state=0)

In [29]:
#checking accurcy of model testing data set
from sklearn.metrics import accuracy_score

In [30]:
precdiction_test=clf.predict(x_test)
accuracy_score(y_test,precdiction_test)

0.9444444444444444

In [31]:
#checking accurcy of model testing data set
precdiction_train=clf.predict(x_train)
accuracy_score(y_train,precdiction_train)

0.979381443298969

In [32]:
#classification report test dataset
from sklearn.metrics import classification_report,confusion_matrix

In [33]:
print(classification_report(y_test,precdiction_test))
print(confusion_matrix(y_test,precdiction_test))

              precision    recall  f1-score   support

           0       0.90      1.00      0.95         9
           1       1.00      0.89      0.94         9

    accuracy                           0.94        18
   macro avg       0.95      0.94      0.94        18
weighted avg       0.95      0.94      0.94        18

[[9 0]
 [1 8]]


In [34]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier,GradientBoostingClassifier,BaggingClassifier

In [35]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import train_test_split

In [36]:
abc=AdaBoostClassifier()
abc.fit(x_train,y_train)

AdaBoostClassifier()

In [37]:
y_pred = abc.predict(x_test)
y_pred_prob = abc.predict_proba(x_test)

In [38]:
print('Training Score : ',abc.score(x_train,y_train))
print('Testing Score : ',abc.score(x_test,y_test))

Training Score :  0.8258877434135166
Testing Score :  0.7777777777777778


In [39]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[7 2]
 [2 7]]
              precision    recall  f1-score   support

           0       0.78      0.78      0.78         9
           1       0.78      0.78      0.78         9

    accuracy                           0.78        18
   macro avg       0.78      0.78      0.78        18
weighted avg       0.78      0.78      0.78        18



In [40]:
gb = GradientBoostingClassifier()
gb.fit(x_train,y_train)
y_pred = gb.predict(x_test)
y_pred_prob = gb.predict_proba(x_test)

In [41]:
print('Training Score : ',gb.score(x_train,y_train))
print('Testing Score : ',gb.score(x_test,y_test))

Training Score :  0.8957617411225659
Testing Score :  0.8888888888888888


In [42]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[9 0]
 [2 7]]
              precision    recall  f1-score   support

           0       0.82      1.00      0.90         9
           1       1.00      0.78      0.88         9

    accuracy                           0.89        18
   macro avg       0.91      0.89      0.89        18
weighted avg       0.91      0.89      0.89        18



In [43]:
bz=BaggingClassifier()
bz.fit(x_train,y_train)
y_pred = gb.predict(x_test)
y_pred_prob = gb.predict_proba(x_test)

In [44]:
print('Training Score : ',bz.score(x_train,y_train))
print('Testing Score : ',bz.score(x_test,y_test))

Training Score :  0.9599083619702177
Testing Score :  0.8333333333333334


In [45]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[9 0]
 [2 7]]
              precision    recall  f1-score   support

           0       0.82      1.00      0.90         9
           1       1.00      0.78      0.88         9

    accuracy                           0.89        18
   macro avg       0.91      0.89      0.89        18
weighted avg       0.91      0.89      0.89        18



In [46]:
from xgboost import XGBClassifier
xgb= XGBClassifier()
xgb.fit(x_train,y_train)
y_pred = xgb.predict(x_test)
y_pred_prob = xgb.predict_proba(x_test)

In [47]:
print('Training Score : ',xgb.score(x_train,y_train))
print('Testing Score : ',xgb.score(x_test,y_test))

Training Score :  0.9518900343642611
Testing Score :  0.8333333333333334


In [48]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[9 0]
 [3 6]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86         9
           1       1.00      0.67      0.80         9

    accuracy                           0.83        18
   macro avg       0.88      0.83      0.83        18
weighted avg       0.88      0.83      0.83        18



In [49]:
#LogisticRegression
from sklearn.linear_model import LogisticRegression

In [50]:
x=df[["Pclass","Sex","Age","Fare"]]
y=df["Survived"]

In [51]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.02, random_state =1)

In [52]:
lg=LogisticRegression()
lg.fit(x_train,y_train)

LogisticRegression()

In [53]:
from sklearn.metrics import accuracy_score
precdiction_test=lg.predict(x_test)
accuracy_score(y_test,precdiction_test)

0.7777777777777778

In [54]:
print(classification_report(y_test,precdiction_test))
print(confusion_matrix(y_test,precdiction_test))

              precision    recall  f1-score   support

           0       0.78      0.78      0.78         9
           1       0.78      0.78      0.78         9

    accuracy                           0.78        18
   macro avg       0.78      0.78      0.78        18
weighted avg       0.78      0.78      0.78        18

[[7 2]
 [2 7]]


In [55]:
from sklearn.neighbors import KNeighborsClassifier

In [56]:
kn=KNeighborsClassifier()
kn.fit(x_train,y_train)

KNeighborsClassifier()

In [57]:
from sklearn.metrics import accuracy_score
precdiction_test=kn.predict(x_test)
accuracy_score(y_test,precdiction_test)

0.5555555555555556

In [58]:
print(classification_report(y_test,precdiction_test))
print(confusion_matrix(y_test,precdiction_test))

              precision    recall  f1-score   support

           0       0.56      0.56      0.56         9
           1       0.56      0.56      0.56         9

    accuracy                           0.56        18
   macro avg       0.56      0.56      0.56        18
weighted avg       0.56      0.56      0.56        18

[[5 4]
 [4 5]]


In [59]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [60]:
from sklearn.svm import SVC
classifier = SVC(kernel = "linear", random_state = 0)
classifier.fit(x_train, y_train)

SVC(kernel='linear', random_state=0)

In [61]:
y_pred = classifier.predict(x_test)

In [62]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test,y_pred)*100

[[8 1]
 [2 7]]


83.33333333333334