In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("titanic.csv")
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
151          152         1       1   
152          153         0       3   
153          154         0       3   
154          155         0       3   
155          156         0       1   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
151                  Pears, Mrs. Thomas (Edith Wearne)  female  22.0      1   
152                                   Meo, Mr. Alfonzo    male  55.5      0   
153                    van Billiard, Mr. Austin Blyler    male  40.5      0   
154                              Olsen, Mr. Ole Martin    male   NaN      0   
155                        Williams, Mr. Charles Duane    male  51.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
151      0            113776  66.6000    C2        S  
152      0        A.5. 11206   8.0500   NaN        S  
153      2          A/5. 851  14.5000   NaN        S  
154      0         Fa 265302   7.3125   NaN        S  
155      1          PC 17597  61.3792   NaN        C  

[156 rows x 12 columns]

In [3]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
df=df[["Survived","Pclass","Sex","Age","Fare"]]

In [5]:
df.head()

Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [6]:
#cleaning data set
df.isnull().sum()

Survived     0
Pclass       0
Sex          0
Age         30
Fare         0
dtype: int64

In [7]:
df.groupby("Sex")["Age"].mean()

Sex
female    24.468085
male      30.326962
Name: Age, dtype: float64

In [8]:
df["Age"]=df.groupby("Sex")["Age"].transform(lambda x:x.fillna(x.mean()))

C:\Users\sonaw\AppData\Local\Temp/ipykernel_2844/2807126402.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"]=df.groupby("Sex")["Age"].transform(lambda x:x.fillna(x.mean()))


In [9]:
#changing column in numerical value
from sklearn.preprocessing import LabelEncoder

In [10]:
le = LabelEncoder()

In [11]:
df["Sex"]=le.fit_transform(df.Sex)

C:\Users\sonaw\AppData\Local\Temp/ipykernel_2844/4032670627.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Sex"]=le.fit_transform(df.Sex)


In [12]:
x=df[["Pclass","Sex","Age","Fare"]]
y=df["Survived"]

In [13]:
#spliting
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.02, random_state =1)

In [14]:
#tarining model
from sklearn.tree import DecisionTreeClassifier

In [15]:
clf=DecisionTreeClassifier(random_state=0,criterion="gini")
clf.fit(x_train,y_train)

DecisionTreeClassifier(random_state=0)

In [16]:
#checking accurcy of model testing data set
from sklearn.metrics import accuracy_score

In [17]:
precdiction_test=clf.predict(x_test)
accuracy_score(y_test,precdiction_test)

1.0

In [18]:
#checking accurcy of model testing data set
precdiction_train=clf.predict(x_train)
accuracy_score(y_train,precdiction_train)

1.0

In [19]:
#classification report test dataset
from sklearn.metrics import classification_report,confusion_matrix

In [20]:
print(classification_report(y_test,precdiction_test))
print(confusion_matrix(y_test,precdiction_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         3
           1       1.00      1.00      1.00         1

    accuracy                           1.00         4
   macro avg       1.00      1.00      1.00         4
weighted avg       1.00      1.00      1.00         4

[[3 0]
 [0 1]]


In [21]:
#classification report train dataset
print(classification_report(y_train,precdiction_train))
print(confusion_matrix(y_train,precdiction_train))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        99
           1       1.00      1.00      1.00        53

    accuracy                           1.00       152
   macro avg       1.00      1.00      1.00       152
weighted avg       1.00      1.00      1.00       152

[[99  0]
 [ 0 53]]


In [22]:
#finding false postive rate and true postive rate
from sklearn.metrics import roc_curve,auc
from sklearn.metrics import roc_curve

In [23]:
dt_probs=clf.predict_proba(x_test)[:,1]

In [24]:
fpr_dt,trp_dt,thresholds_dt=roc_curve(y_test,dt_probs)

In [25]:
#score
auc_score_dt=auc(fpr_dt,trp_dt)
auc_score_dt

1.0

In [26]:
# RandomForest
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [27]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.02, random_state =1)

In [28]:
clf=RandomForestClassifier(random_state=0,criterion="gini")
clf.fit(x_train,y_train)

RandomForestClassifier(random_state=0)

In [29]:
#checking accurcy of model testing data set
from sklearn.metrics import accuracy_score

In [30]:
precdiction_test=clf.predict(x_test)
accuracy_score(y_test,precdiction_test)

1.0

In [31]:
#checking accurcy of model testing data set
precdiction_train=clf.predict(x_train)
accuracy_score(y_train,precdiction_train)

1.0

In [32]:
#classification report test dataset
from sklearn.metrics import classification_report,confusion_matrix

In [33]:
print(classification_report(y_test,precdiction_test))
print(confusion_matrix(y_test,precdiction_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         3
           1       1.00      1.00      1.00         1

    accuracy                           1.00         4
   macro avg       1.00      1.00      1.00         4
weighted avg       1.00      1.00      1.00         4

[[3 0]
 [0 1]]


In [34]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier,GradientBoostingClassifier,BaggingClassifier

In [35]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import train_test_split

In [36]:
abc=AdaBoostClassifier()
abc.fit(x_train,y_train)

AdaBoostClassifier()

In [37]:
y_pred = abc.predict(x_test)
y_pred_prob = abc.predict_proba(x_test)

In [38]:
print('Training Score : ',abc.score(x_train,y_train))
print('Testing Score : ',abc.score(x_test,y_test))

Training Score :  0.881578947368421
Testing Score :  1.0


In [39]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[3 0]
 [0 1]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         3
           1       1.00      1.00      1.00         1

    accuracy                           1.00         4
   macro avg       1.00      1.00      1.00         4
weighted avg       1.00      1.00      1.00         4



In [40]:
gb = GradientBoostingClassifier()
gb.fit(x_train,y_train)
y_pred = gb.predict(x_test)
y_pred_prob = gb.predict_proba(x_test)

In [41]:
print('Training Score : ',gb.score(x_train,y_train))
print('Testing Score : ',gb.score(x_test,y_test))

Training Score :  0.9868421052631579
Testing Score :  0.75


In [42]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[2 1]
 [0 1]]
              precision    recall  f1-score   support

           0       1.00      0.67      0.80         3
           1       0.50      1.00      0.67         1

    accuracy                           0.75         4
   macro avg       0.75      0.83      0.73         4
weighted avg       0.88      0.75      0.77         4



In [43]:
bz=BaggingClassifier()
bz.fit(x_train,y_train)
y_pred = gb.predict(x_test)
y_pred_prob = gb.predict_proba(x_test)

In [44]:
print('Training Score : ',bz.score(x_train,y_train))
print('Testing Score : ',bz.score(x_test,y_test))

Training Score :  0.9736842105263158
Testing Score :  1.0


In [45]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[2 1]
 [0 1]]
              precision    recall  f1-score   support

           0       1.00      0.67      0.80         3
           1       0.50      1.00      0.67         1

    accuracy                           0.75         4
   macro avg       0.75      0.83      0.73         4
weighted avg       0.88      0.75      0.77         4



In [46]:
from xgboost import XGBClassifier
xgb= XGBClassifier()
xgb.fit(x_train,y_train)
y_pred = xgb.predict(x_test)
y_pred_prob = xgb.predict_proba(x_test)

In [47]:
print('Training Score : ',xgb.score(x_train,y_train))
print('Testing Score : ',xgb.score(x_test,y_test))

Training Score :  0.993421052631579
Testing Score :  0.75


In [48]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[2 1]
 [0 1]]
              precision    recall  f1-score   support

           0       1.00      0.67      0.80         3
           1       0.50      1.00      0.67         1

    accuracy                           0.75         4
   macro avg       0.75      0.83      0.73         4
weighted avg       0.88      0.75      0.77         4



In [49]:
#LogisticRegression
from sklearn.linear_model import LogisticRegression

In [50]:
x=df[["Pclass","Sex","Age","Fare"]]
y=df["Survived"]

In [51]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.02, random_state =1)

In [52]:
lg=LogisticRegression()
lg.fit(x_train,y_train)

LogisticRegression()

In [53]:
from sklearn.metrics import accuracy_score
precdiction_test=lg.predict(x_test)
accuracy_score(y_test,precdiction_test)

1.0

In [54]:
print(classification_report(y_test,precdiction_test))
print(confusion_matrix(y_test,precdiction_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         3
           1       1.00      1.00      1.00         1

    accuracy                           1.00         4
   macro avg       1.00      1.00      1.00         4
weighted avg       1.00      1.00      1.00         4

[[3 0]
 [0 1]]


In [55]:
from sklearn.neighbors import KNeighborsClassifier

In [56]:
kn=KNeighborsClassifier()
kn.fit(x_train,y_train)

KNeighborsClassifier()

In [57]:
from sklearn.metrics import accuracy_score
precdiction_test=kn.predict(x_test)
accuracy_score(y_test,precdiction_test)

0.5

In [58]:
print(classification_report(y_test,precdiction_test))
print(confusion_matrix(y_test,precdiction_test))

              precision    recall  f1-score   support

           0       0.67      0.67      0.67         3
           1       0.00      0.00      0.00         1

    accuracy                           0.50         4
   macro avg       0.33      0.33      0.33         4
weighted avg       0.50      0.50      0.50         4

[[2 1]
 [1 0]]


In [59]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [60]:
from sklearn.svm import SVC
classifier = SVC(kernel = "linear", random_state = 0)
classifier.fit(x_train, y_train)

SVC(kernel='linear', random_state=0)

In [61]:
y_pred = classifier.predict(x_test)

In [62]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test,y_pred)*100

[[3 0]
 [0 1]]


100.0