Q6) Use Digits dataset. Handle the null values and convert the categorical values into numerical values. Make a
classification model based on type of logistic regression model that having no quantitative significance i.e.
target variable that can have 3 or more possible unordered types

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("digits.csv")
df

0  0.1   5  13   9   1  0.2  0.3  0.4  0.5  ...  0.23  0.24  0.25  6  \
0     0    0   0  12  13   5    0    0    0    0  ...     0     0     0  0   
1     0    0   0   4  15  12    0    0    0    0  ...     0     0     0  0   
2     0    0   7  15  13   1    0    0    0    8  ...     0     0     0  7   
3     0    0   0   1  11   0    0    0    0    0  ...     0     0     0  0   
4     0    0  12  10   0   0    0    0    0    0  ...     0     0     0  9   
...  ..  ...  ..  ..  ..  ..  ...  ...  ...  ...  ...   ...   ...   ... ..   
1791  0    0   4  10  13   6    0    0    0    1  ...     0     0     0  2   
1792  0    0   6  16  13  11    1    0    0    0  ...     0     0     0  6   
1793  0    0   1  11  15   1    0    0    0    0  ...     0     0     0  2   
1794  0    0   2  10   7   0    0    0    0    0  ...     0     0     0  5   
1795  0    0  10  14   8   1    0    0    0    2  ...     0     0     1  8   

      13.2  10.2  0.26  0.27  0.28  0.29  
0       11    16    10     0     0     1  
1        3    11    16     9     0     2  
2       13    13     9     0     0     3  
3        2    16     4     0     0     4  
4       16    16    10     0     0     5  
...    ...   ...   ...   ...   ...   ...  
1791    14    15     9     0     0     9  
1792    16    14     6     0     0     0  
1793     9    13     6     0     0     8  
1794    12    16    12     0     0     9  
1795    12    14    12     1     0     8  

[1796 rows x 65 columns]

In [3]:
df.head(50)

0  0.1   5  13   9   1  0.2  0.3  0.4  0.5  ...  0.23  0.24  0.25   6  \
0   0    0   0  12  13   5    0    0    0    0  ...     0     0     0   0   
1   0    0   0   4  15  12    0    0    0    0  ...     0     0     0   0   
2   0    0   7  15  13   1    0    0    0    8  ...     0     0     0   7   
3   0    0   0   1  11   0    0    0    0    0  ...     0     0     0   0   
4   0    0  12  10   0   0    0    0    0    0  ...     0     0     0   9   
5   0    0   0  12  13   0    0    0    0    0  ...     0     0     0   1   
6   0    0   7   8  13  16   15    1    0    0  ...     0     0     0  13   
7   0    0   9  14   8   1    0    0    0    0  ...     0     0     0  11   
8   0    0  11  12   0   0    0    0    0    2  ...     0     0     0   9   
9   0    0   1   9  15  11    0    0    0    0  ...     0     0     0   1   
10  0    0   0   0  14  13    1    0    0    0  ...     0     0     0   0   
11  0    0   5  12   1   0    0    0    0    0  ...     2     0     0   3   
12  0    2   9  15  14   9    3    0    0    4  ...     0     0     2  12   
13  0    0   0   8  15   1    0    0    0    0  ...     0     0     0   0   
14  0    5  12  13  16  16    2    0    0   11  ...     0     0     4  15   
15  0    0   0   8  15   1    0    0    0    0  ...     2     0     0   0   
16  0    0   1   8  15  10    0    0    0    3  ...     0     0     0   0   
17  0    0  10   7  13   9    0    0    0    0  ...     0     0     0  11   
18  0    0   6  14   4   0    0    0    0    0  ...     2     0     0   7   
19  0    0   3  13  11   7    0    0    0    0  ...     0     0     0   2   
20  0    0   0   2  16  16    2    0    0    0  ...     0     0     0   0   
21  0    0   8  16   5   0    0    0    0    1  ...     0     0     0   7   
22  0    1   8  12  15  14    4    0    0    3  ...     0     0     0  14   
23  0    0   0   0  12   2    0    0    0    0  ...     0     0     0   0   
24  0    0  12   8   8   7    0    0    0    3  ...     0     0     0  11   
25  0    0   1  13  14   3    0    0    0    0  ...     0     0     0   3   
26  0    0   0   8  14  14    2    0    0    0  ...     0     0     0   0   
27  0    0  10  11   4   0    0    0    0    0  ...     0     0     0   8   
28  0    0   9  13   7   0    0    0    0    0  ...     2     0     0   7   
29  0    0  10  14  11   3    0    0    0    4  ...     0     0     0  11   
30  0    0   2  13   8   0    0    0    0    0  ...     2     0     0   2   
31  0    2  13  16  16  16   11    0    0    5  ...     0     0     2  16   
32  0    6  13   5   8   8    1    0    0    8  ...     0     0     4  16   
33  0    0   0   5  14   2    0    0    0    0  ...     0     0     0   0   
34  0    3  15   8   8   6    0    0    0    4  ...     0     0     1  15   
35  0    0   6  14  10   2    0    0    0    0  ...     0     0     0   7   
36  0    0  13  10   1   0    0    0    0    5  ...     0     0     0  13   
37  0    0   7   7  13  16    4    0    0    0  ...     0     0     1  11   
38  0    1   9  16  13   7    0    0    0    7  ...     0     0     0   9   
39  0    0  11  10  12   4    0    0    0    0  ...     0     0     1  11   
40  0    0   0   9  15   1    0    0    0    0  ...     0     0     0   0   
41  0    0   0   0  12   5    0    0    0    0  ...     0     0     0   0   
42  0    0   0   9  15  12    0    0    0    0  ...     0     0     0   0   
43  0    0   9  16  16  16    5    0    0    1  ...     0     0     0  13   
44  0    0   9  16  13   6    0    0    0    0  ...     0     0     0  11   
45  0    1  15   4   0   0    0    0    0    2  ...     0     0     0  14   
46  0    0   0   1  11   9    0    0    0    0  ...     0     0     0   0   
47  0    0   2  15  13   3    0    0    0    0  ...     0     0     0   4   
48  0    0   1  15  13   1    0    0    0    0  ...     0     0     0   0   
49  0    0   0   5  14  12    2    0    0    0  ...     0     0     0   0   

    13.2  10.2  0.26  0.27  0.28  0.29  
0     11    16    10     0     0   

In [4]:
df.describe()

0          0.1            5           13            9  \
count  1796.0  1796.000000  1796.000000  1796.000000  1796.000000   
mean      0.0     0.304009     5.204900    11.835189    11.849666   
std       0.0     0.907416     4.756148     4.249936     4.288055   
min       0.0     0.000000     0.000000     0.000000     0.000000   
25%       0.0     0.000000     1.000000    10.000000    10.000000   
50%       0.0     0.000000     4.000000    13.000000    13.000000   
75%       0.0     0.000000     9.000000    15.000000    15.000000   
max       0.0     8.000000    16.000000    16.000000    16.000000   

                 1          0.2          0.3          0.4          0.5  ...  \
count  1796.000000  1796.000000  1796.000000  1796.000000  1796.000000  ...   
mean      5.784521     1.363029     0.129733     0.005568     1.994989  ...   
std       5.666871     3.326546     1.037667     0.094248     3.196704  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       4.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%      11.000000     0.000000     0.000000     0.000000     3.000000  ...   
max      16.000000    16.000000    15.000000     2.000000    16.000000  ...   

              0.23         0.24         0.25           6        13.2  \
count  1796.000000  1796.000000  1796.000000  1796.00000  1796.00000   
mean      0.206570     0.000557     0.279510     5.55735    12.08853   
std       0.984663     0.023596     0.934539     5.10443     4.37586   
min       0.000000     0.000000     0.000000     0.00000     0.00000   
25%       0.000000     0.000000     0.000000     1.00000    11.00000   
50%       0.000000     0.000000     0.000000     4.00000    13.00000   
75%       0.000000     0.000000     0.000000    10.00000    16.00000   
max      13.000000     1.000000     9.000000    16.00000    16.00000   

              10.2         0.26         0.27         0.28         0.29  
count  1796.000000  1796.000000  1796.000000  1796.000000  1796.000000  
mean     11.810134     6.767817     2.069042     0.364699     4.493318  
std       4.935137     5.900105     4.091396     1.860620     2.864140  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%      10.000000     0.000000     0.000000     0.000000     2.000000  
50%      14.000000     6.000000     0.000000     0.000000     4.000000  
75%      16.000000    12.000000     2.000000     0.000000     7.000000  
max      16.000000    16.000000    16.000000    16.000000     9.000000  

[8 rows x 65 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1796 entries, 0 to 1795
Data columns (total 65 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       1796 non-null   int64
 1   0.1     1796 non-null   int64
 2   5       1796 non-null   int64
 3   13      1796 non-null   int64
 4   9       1796 non-null   int64
 5   1       1796 non-null   int64
 6   0.2     1796 non-null   int64
 7   0.3     1796 non-null   int64
 8   0.4     1796 non-null   int64
 9   0.5     1796 non-null   int64
 10  13.1    1796 non-null   int64
 11  15      1796 non-null   int64
 12  10      1796 non-null   int64
 13  15.1    1796 non-null   int64
 14  5.1     1796 non-null   int64
 15  0.6     1796 non-null   int64
 16  0.7     1796 non-null   int64
 17  3       1796 non-null   int64
 18  15.2    1796 non-null   int64
 19  2       1796 non-null   int64
 20  0.8     1796 non-null   int64
 21  11      1796 non-null   int64
 22  8       1796 non-null   int64
 23  0.9     1796 

In [6]:
df.columns

Index(['0', '0.1', '5', '13', '9', '1', '0.2', '0.3', '0.4', '0.5', '13.1',
       '15', '10', '15.1', '5.1', '0.6', '0.7', '3', '15.2', '2', '0.8', '11',
       '8', '0.9', '0.10', '4', '12', '0.11', '0.12', '8.1', '8.2', '0.13',
       '0.14', '5.2', '8.3', '0.15', '0.16', '9.1', '8.4', '0.17', '0.18',
       '4.1', '11.1', '0.19', '1.1', '12.1', '7', '0.20', '0.21', '2.1', '14',
       '5.3', '10.1', '12.2', '0.22', '0.23', '0.24', '0.25', '6', '13.2',
       '10.2', '0.26', '0.27', '0.28', '0.29'],
      dtype='object')

In [7]:
df.columns

Index(['0', '0.1', '5', '13', '9', '1', '0.2', '0.3', '0.4', '0.5', '13.1',
       '15', '10', '15.1', '5.1', '0.6', '0.7', '3', '15.2', '2', '0.8', '11',
       '8', '0.9', '0.10', '4', '12', '0.11', '0.12', '8.1', '8.2', '0.13',
       '0.14', '5.2', '8.3', '0.15', '0.16', '9.1', '8.4', '0.17', '0.18',
       '4.1', '11.1', '0.19', '1.1', '12.1', '7', '0.20', '0.21', '2.1', '14',
       '5.3', '10.1', '12.2', '0.22', '0.23', '0.24', '0.25', '6', '13.2',
       '10.2', '0.26', '0.27', '0.28', '0.29'],
      dtype='object')

In [8]:
from sklearn.linear_model import LogisticRegression

In [9]:
y = df['0.1']
x = df[df.columns[1:]]

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state=10)

In [11]:
lg=LogisticRegression()
lg.fit(x_train,y_train)

C:\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [12]:
lg.score(x_train,y_train)

0.9851521900519673

In [13]:
lg.score(x_test,y_test)

0.910913140311804

In [14]:
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import accuracy_score
precdiction_test=lg.predict(x_test)
accuracy_score(y_test,precdiction_test)

0.910913140311804

In [15]:
print(classification_report(y_test,precdiction_test))
print(confusion_matrix(y_test,precdiction_test))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       372
           1       0.78      0.81      0.79        36
           2       0.37      0.37      0.37        19
           3       0.18      0.22      0.20         9
           4       0.30      0.33      0.32         9
           5       0.00      0.00      0.00         2
           6       0.00      0.00      0.00         1
           8       0.00      0.00      0.00         1

    accuracy                           0.91       449
   macro avg       0.33      0.34      0.33       449
weighted avg       0.91      0.91      0.91       449

[[368   0   2   2   0   0   0   0]
 [  1  29   5   0   1   0   0   0]
 [  0   7   7   2   3   0   0   0]
 [  0   1   4   2   1   0   1   0]
 [  0   0   1   3   3   1   1   0]
 [  0   0   0   1   1   0   0   0]
 [  0   0   0   1   0   0   0   0]
 [  0   0   0   0   1   0   0   0]]


C:\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
